version: '2'
services:
  nc_db:
    image: linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Europe/London
    volumes:
      - /mnt/Containers/mariadb_data:/config
    networks:
      - net01
    restart: always
  nc_web:
    image: nextcloud
    volumes:
      - /mnt/Containers/nextcloud_data:/var/www/html/
    networks:
      - net01
    restart: always
    depends_on:
      - db
networks:
  net01:
    external:
      name: net01